export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL'

export const REPLY_CREATE_REQUEST = 'REPLY_CREATE_REQUEST'
export const REPLY_CREATE_SUCCESS = 'REPLY_CREATE_SUCCESS'
export const REPLY_CREATE_FAIL = 'REPLY_CREATE_FAIL'

export const REPLY_LIST_REQUEST = 'REPLY_LIST_REQUEST'
export const REPLY_LIST_SUCCESS = 'REPLY_LIST_SUCCESS'
export const REPLY_LIST_FAIL = 'REPLY_LIST_FAIL'